// Generated by scripts/build-catalog-data.mjs from content/catalog.en.json.
// Do not edit by hand: change the JSON and re-run the script.
// Guest-facing copy and published starting prices only; no purchase prices,
// partner payouts or commissions belong in this file.

export const catalogData = {
  "version": "mehmongo-tashkent-2026-09-05-final",
  "locale": "en",
  "departureCity": "Tashkent",
  "currency": "USD",
  "page": {
    "eyebrow": "YOUR STAY, YOUR PLANS",
    "title": "A little planning. A lot more Tashkent.",
    "intro": "A local guide, a mountain escape or your next ride. Choose what you need and let MehmonGo help arrange the details.",
    "primaryCta": "Explore services",
    "trustItems": [
      "No account needed",
      "Price confirmed before payment",
      "Help from our team"
    ],
    "sectionTitle": "What would make your stay better?",
    "sectionIntro": "Start with an idea. We will help with the details.",
    "filters": [
      {
        "id": "all",
        "label": "All services"
      },
      {
        "id": "tours",
        "label": "Tours & guides"
      },
      {
        "id": "transport",
        "label": "Private rides"
      },
      {
        "id": "tickets",
        "label": "Flights, trains & buses"
      }
    ],
    "stepsTitle": "From an idea to a plan",
    "steps": [
      {
        "title": "Choose your service",
        "text": "Pick a ride, an experience or a ticket request."
      },
      {
        "title": "We confirm the details",
        "text": "Our team contacts you with availability, the full price and payment instructions."
      },
      {
        "title": "Confirm and enjoy",
        "text": "Pay as agreed, then receive your pickup or booking details."
      }
    ],
    "priceNote": "Starting prices are in USD for the option described. We confirm the final price and the amount payable in UZS before payment. Extra services are quoted separately.",
    "paymentNote": "No payment is taken on this website. Your request is not a confirmed booking.",
    "customTitle": "Have something else in mind?",
    "customText": "A larger group, a different route or a special request? Tell us your plans and we will check the options.",
    "customCta": "Ask for a custom quote",
    "restaurantTitle": "A table for your evening",
    "restaurantText": "Tell us your preferred food, time and group size. We will check availability and any reservation conditions.",
    "restaurantCta": "Request a restaurant reservation",
    "emptyCategory": "No services are available in this category for your hotel right now."
  },
  "offers": [
    {
      "id": "tashkent-private-guide",
      "category": "tours",
      "featured": true,
      "title": "See Tashkent with a local guide",
      "eyebrow": "PRIVATE EXCURSION · TASHKENT",
      "summary": "Turn a city walk into stories worth taking home. Tell us what interests you, and we will match the excursion to your plans.",
      "description": "Curious about the old city, local food or everyday life? Ask for a route around your interests. We confirm the guide, language, duration and group size before you pay.",
      "price": {
        "mode": "from",
        "amount": 120,
        "currency": "USD",
        "unit": "per agreed excursion",
        "billingUnit": "excursion"
      },
      "image": "assets/tashkent-tv-tower.jpg",
      "imageAlt": "Tashkent seen from above at sunset, with the television tower above the city",
      "imageFit": "cover",
      "imageCaption": "Tashkent inspiration. Your route is agreed separately.",
      "facts": [
        "Private guide",
        "Language agreed in advance",
        "Route tailored to your interests"
      ],
      "includes": [
        "A guide for one agreed excursion"
      ],
      "extras": [
        "Transport, attraction tickets and meals unless included in your quote"
      ],
      "confirmBeforePayment": [
        "Guide availability and language",
        "Excursion duration, route and meeting point",
        "Group size and final total"
      ],
      "requestProfile": "guide",
      "cta": "Request this excursion"
    },
    {
      "id": "tashkent-mountains-base",
      "category": "tours",
      "featured": true,
      "title": "Trade the city for mountain views",
      "eyebrow": "MOUNTAIN DAY TRIP · FROM TASHKENT",
      "summary": "Fresh air, open views and a change of pace. Ask us about a route towards Chimgan, Charvak or Amirsoy.",
      "description": "Tell us whether you prefer mountain scenery, a lakeside stop or a resort visit. We will confirm a route and vehicle for your day out from Tashkent. The starting price covers one agreed route, not every destination together.",
      "price": {
        "mode": "from",
        "amount": 160,
        "currency": "USD",
        "unit": "per vehicle · agreed day-trip route",
        "billingUnit": "vehicle_route"
      },
      "image": "assets/charvak-lake.jpg",
      "imageAlt": "Turquoise Charvak reservoir below the mountains near Tashkent",
      "imageFit": "cover",
      "imageCaption": "Charvak inspiration. Stops depend on your confirmed route.",
      "facts": [
        "Departure from Tashkent",
        "Private vehicle with driver",
        "Route confirmed with you"
      ],
      "includes": [
        "Private vehicle with driver for the agreed mountain route"
      ],
      "extras": [
        "Cable cars, attraction tickets, guide and meals unless included in your quote"
      ],
      "confirmBeforePayment": [
        "Exact route, stops and return arrangement",
        "Schedule, road and weather conditions",
        "Vehicle, passenger and luggage capacity",
        "Full price, including any parking or route charges"
      ],
      "requestProfile": "mountains",
      "cta": "Plan my mountain day"
    },
    {
      "id": "tashkent-city-car",
      "category": "transport",
      "featured": true,
      "title": "Your own pace. Your own city day.",
      "eyebrow": "PRIVATE CAR & DRIVER · TASHKENT",
      "summary": "Make time for the places you want to see. A private car and driver help you move between your agreed city stops.",
      "description": "Plan a day around your interests without arranging a new ride at every stop. This is a car-and-driver service within Tashkent, available for the agreed 09:00–18:00 schedule. A sightseeing guide can be quoted separately.",
      "price": {
        "mode": "from",
        "amount": 140,
        "currency": "USD",
        "unit": "per vehicle · 09:00–18:00",
        "billingUnit": "vehicle_day"
      },
      "image": "assets/tashkent-chorsu-bazaar.jpg",
      "imageAlt": "The blue tiled dome of Chorsu Bazaar in Tashkent with shoppers at the entrance",
      "imageFit": "cover",
      "imageCaption": "City inspiration. Stops are agreed before confirmation.",
      "facts": [
        "Car and driver",
        "09:00–18:00",
        "Fuel and parking included"
      ],
      "includes": [
        "Private car and driver within Tashkent for 09:00–18:00",
        "Fuel and parking for the agreed city service"
      ],
      "extras": [
        "Professional guide, attraction tickets and meals",
        "Additional hours or trips outside the agreed area"
      ],
      "confirmBeforePayment": [
        "Date, pickup point and city itinerary",
        "Vehicle and passenger capacity",
        "Any extra hours and their price"
      ],
      "requestProfile": "city",
      "cta": "Plan my city day"
    },
    {
      "id": "tashkent-airport-sedan",
      "category": "transport",
      "featured": true,
      "title": "Your airport ride, arranged",
      "eyebrow": "AIRPORT TRANSFER · UP TO 3 PASSENGERS",
      "summary": "Start or finish your Tashkent stay with a private ride between the airport and your hotel.",
      "description": "Share your flight, pickup direction and luggage details. We will confirm the meeting point and vehicle so you know what to expect. Need a name-board welcome? Choose the separate meet-and-greet option.",
      "price": {
        "mode": "from",
        "amount": 30,
        "currency": "USD",
        "unit": "per vehicle · one way",
        "billingUnit": "vehicle_one_way"
      },
      "image": "assets/airport-sedan.jpg",
      "imageAlt": "Sedan pictured in the supplier vehicle catalogue",
      "imageFit": "contain",
      "imageCaption": "Vehicle example; the assigned car is confirmed separately.",
      "facts": [
        "Private sedan",
        "Up to 3 passengers",
        "Airport ↔ Tashkent hotel"
      ],
      "includes": [
        "One private airport transfer in the confirmed direction"
      ],
      "extras": [
        "Extra stops, waiting and special requests if quoted",
        "Name-board meet-and-greet is a separate option"
      ],
      "confirmBeforePayment": [
        "Flight, date and pickup time",
        "Passenger and luggage fit",
        "Meeting point, waiting policy and full price"
      ],
      "requestProfile": "airport",
      "cta": "Arrange my airport ride"
    },
    {
      "id": "tashkent-airport-minivan",
      "category": "transport",
      "featured": true,
      "title": "Arrive together, travel together",
      "eyebrow": "AIRPORT MINIVAN · UP TO 5 PASSENGERS",
      "summary": "One private ride for your family or small group. Tell us how many people and bags are travelling.",
      "description": "Keep your group together between Tashkent airport and your hotel. Passenger numbers alone do not guarantee luggage space: we check both before confirming your vehicle.",
      "price": {
        "mode": "from",
        "amount": 40,
        "currency": "USD",
        "unit": "per vehicle · one way",
        "billingUnit": "vehicle_one_way"
      },
      "image": "assets/family-minivan.jpg",
      "imageAlt": "Kia Carnival minivan pictured in the supplier catalogue",
      "imageFit": "contain",
      "imageCaption": "Vehicle example; model and luggage capacity are confirmed.",
      "facts": [
        "Private minivan",
        "Up to 5 passengers",
        "Luggage space checked first"
      ],
      "includes": [
        "One private airport transfer in the confirmed direction"
      ],
      "extras": [
        "Extra stops, waiting and child seats if available and quoted",
        "Name-board meet-and-greet is a separate option"
      ],
      "confirmBeforePayment": [
        "Flight, direction and pickup time",
        "Passengers, bags and any child-seat request",
        "Vehicle, waiting policy and final price"
      ],
      "requestProfile": "airport",
      "cta": "Arrange our minivan"
    },
    {
      "id": "tashkent-samarkand-one-way",
      "category": "transport",
      "featured": true,
      "title": "Next stop: Samarkand",
      "eyebrow": "TASHKENT → SAMARKAND · ONE WAY",
      "summary": "Keep your onward journey simple with a private driver. We arrange the pickup and destination with you.",
      "description": "Ready for the next part of your trip? Send your Tashkent pickup address and Samarkand destination. This is an intercity transfer, not a sightseeing tour or a return trip.",
      "price": {
        "mode": "from",
        "amount": 200,
        "currency": "USD",
        "unit": "per vehicle · one way",
        "billingUnit": "vehicle_one_way"
      },
      "image": "assets/samarkand-registan-square.jpg",
      "imageAlt": "The three madrasahs of Registan square in Samarkand under a clear sky",
      "imageFit": "cover",
      "imageCaption": "Destination inspiration. Registan entry and sightseeing are not included.",
      "facts": [
        "Private driver",
        "Tashkent pickup",
        "Samarkand drop-off"
      ],
      "includes": [
        "One private transfer from Tashkent to the agreed Samarkand destination"
      ],
      "extras": [
        "Sightseeing, attraction tickets, guide, meals and a return journey",
        "Unplanned detours or additional stops"
      ],
      "confirmBeforePayment": [
        "Pickup and drop-off addresses, date and time",
        "Vehicle, luggage and passenger capacity",
        "Agreed stops and full price"
      ],
      "requestProfile": "intercity",
      "cta": "Arrange my Samarkand ride"
    },
    {
      "id": "tashkent-airport-welcome",
      "category": "transport",
      "featured": false,
      "title": "A name-board welcome in Tashkent",
      "eyebrow": "AIRPORT ARRIVAL · MEET & GREET",
      "summary": "Prefer someone to meet you with your name? Request a welcome and a private transfer to your Tashkent hotel.",
      "description": "Our team confirms an accessible meeting point, your arrival details and the vehicle before payment. This is a separate transfer package; the price is not an add-on to the sedan or minivan price.",
      "price": {
        "mode": "from",
        "amount": 45,
        "currency": "USD",
        "unit": "per vehicle · arrival package",
        "billingUnit": "vehicle_arrival_package"
      },
      "image": "assets/family-minivan.jpg",
      "imageAlt": "Illustrative vehicle from the supplier catalogue",
      "imageFit": "contain",
      "imageCaption": "Illustrative vehicle; this package does not guarantee a minivan.",
      "facts": [
        "Name-board meeting",
        "Airport → Tashkent hotel",
        "Meeting point confirmed"
      ],
      "includes": [
        "Meeting with a name board at the agreed accessible location",
        "Private transfer to the agreed Tashkent hotel"
      ],
      "extras": [
        "Extra stops, waiting or other additions if quoted"
      ],
      "confirmBeforePayment": [
        "Supplier availability, vehicle and capacity",
        "Flight and accessible meeting point",
        "Waiting conditions and total price"
      ],
      "requestProfile": "airport_arrival",
      "cta": "Request a welcome transfer"
    },
    {
      "id": "ticket-assistance",
      "category": "tickets",
      "featured": true,
      "title": "Where are you heading next?",
      "eyebrow": "FLIGHTS · TRAINS · BUSES",
      "summary": "Tell us your route and travel date. We will search available options and help you buy the ticket that fits your plans.",
      "description": "No single price fits every journey. We check availability and send you the full quote, including any service fee, before you decide. You only pay after agreeing to an available option and its booking conditions.",
      "price": {
        "mode": "quote",
        "amount": null,
        "currency": null,
        "unit": "Full price confirmed before payment",
        "billingUnit": null
      },
      "image": null,
      "imageAlt": null,
      "imageFit": null,
      "imageCaption": null,
      "facts": [
        "Flight, train or bus",
        "Options checked for your route",
        "Full quote before payment"
      ],
      "includes": [
        "Help searching available options",
        "Booking assistance for the option you approve"
      ],
      "extras": [
        "Ticket fare and any service fee are included in your individual quote",
        "Changes, cancellations and refunds depend on the chosen ticket rules"
      ],
      "confirmBeforePayment": [
        "Route, date, availability and passenger details",
        "Fare, baggage where relevant, service fee and total",
        "Expected ticket delivery time and change/refund conditions"
      ],
      "timing": "We aim to issue your ticket within 15–30 minutes after payment is confirmed, once seats and passenger details have been checked. We will confirm the expected timing before you pay.",
      "requestProfile": "tickets",
      "cta": "Find my ticket"
    }
  ],
  "form": {
    "title": "Let's arrange the details",
    "intro": "Share your plans. Our team will contact you to confirm availability and the full price.",
    "nameLabel": "Your name",
    "contactLabel": "One way to reach you",
    "contactPlaceholder": "Phone with country code, Telegram @username or email",
    "dateLabel": "Preferred date",
    "timeLabel": "Preferred time",
    "countLabel": "Number of travellers",
    "noteLabel": "Anything else? (optional)",
    "submit": "Send my request",
    "sending": "Sending your request…",
    "back": "Back to service",
    "priceLabel": "Starting price — not a confirmed total",
    "quoteLabel": "Individual quote — no payment now",
    "privacy": "We use your name, contact details and request to arrange the service. Do not enter passport or card details here.",
    "payment": "Submitting this form does not charge you or confirm a booking.",
    "successTitle": "Your request is in.",
    "successText": "Keep your request reference. Our team will contact you using the details you provided to confirm availability, the full price and payment instructions.",
    "networkError": "We could not confirm that your request was received. Keep your details here and try again.",
    "rateLimitError": "Several requests have been sent recently. Please wait a few minutes before trying again.",
    "inactiveRoom": "This room link is not available. Please ask your hotel for the current MehmonGo QR code.",
    "helpHint": "If you need help reaching MehmonGo, ask your hotel reception."
  },
  "faq": [
    {
      "question": "Do I pay on this website?",
      "answer": "No. Send a request first. Our team confirms availability, the total amount and payment instructions. Your hotel reception may collect payment under the agreed arrangement."
    },
    {
      "question": "Is the price per person?",
      "answer": "Private rides are priced per vehicle for the option shown. The guide price is per agreed excursion. We confirm group size and any extra costs before payment."
    },
    {
      "question": "Is my booking confirmed when I send a request?",
      "answer": "Not yet. We contact you to agree on the details and explain how to confirm your booking."
    },
    {
      "question": "Can I change or cancel?",
      "answer": "Conditions depend on the service and supplier. We explain any change or cancellation terms before you pay."
    }
  ]
} as const;
