// Generated by scripts/build-catalog-images.mjs.
// Intrinsic sizes of the committed catalogue photos, so cards reserve space
// before the image loads. Sources and licences: content/photo-sources.json
// and the /photo-credits page.

export type CatalogImageVariant = {
  fit: 'cover' | 'contain';
  width: number;
  height: number;
  widths: number[];
};

export const catalogImages: Record<string, CatalogImageVariant> = {
  "tashkent-tv-tower": {
    "fit": "cover",
    "width": 960,
    "height": 640,
    "widths": [
      480,
      960
    ]
  },
  "tashkent-chorsu-bazaar": {
    "fit": "cover",
    "width": 960,
    "height": 640,
    "widths": [
      480,
      960
    ]
  },
  "charvak-lake": {
    "fit": "cover",
    "width": 960,
    "height": 640,
    "widths": [
      480,
      960
    ]
  },
  "samarkand-registan-square": {
    "fit": "cover",
    "width": 960,
    "height": 640,
    "widths": [
      480,
      960
    ]
  },
  "airport-sedan": {
    "fit": "contain",
    "width": 960,
    "height": 504,
    "widths": [
      480,
      960
    ]
  },
  "family-minivan": {
    "fit": "contain",
    "width": 600,
    "height": 400,
    "widths": [
      480,
      960
    ]
  }
};
