// Generated by scripts/build-catalog-data.mjs from content/catalog.{ru,uz,zh}.json.
// Do not edit by hand: change the JSON and re-run the script.
// Guest-facing text in the other languages. Prices, ids and profiles are read
// from the English catalogue, never from here.

import type { CatalogSource } from '../../supabase/functions/_shared/catalog';

export const catalogTranslations: Record<'ru' | 'uz' | 'zh', CatalogSource> = {
  "ru": {
    "version": "mehmongo-tashkent-2026-09-05-final",
    "locale": "ru",
    "departureCity": "Ташкент",
    "currency": "USD",
    "page": {
      "eyebrow": "ВАШ ОТДЫХ, ВАШИ ПЛАНЫ",
      "title": "Немного планов. Намного больше Ташкента.",
      "intro": "Местный гид, поездка в горы или трансфер. Выберите, что вам нужно, а MehmonGo поможет всё организовать.",
      "primaryCta": "Смотреть услуги",
      "trustItems": [
        "Без регистрации",
        "Цена подтверждается до оплаты",
        "Помощь нашей команды"
      ],
      "sectionTitle": "Что сделает ваш отдых лучше?",
      "sectionIntro": "Начните с идеи. С деталями поможем мы.",
      "filters": [
        {
          "id": "all",
          "label": "Все услуги"
        },
        {
          "id": "tours",
          "label": "Экскурсии и гиды"
        },
        {
          "id": "transport",
          "label": "Трансферы"
        },
        {
          "id": "tickets",
          "label": "Авиа, ж/д и автобусы"
        }
      ],
      "stepsTitle": "От идеи до плана",
      "steps": [
        {
          "title": "Выберите услугу",
          "text": "Поездка, экскурсия или билеты."
        },
        {
          "title": "Мы уточняем детали",
          "text": "Наша команда свяжется с вами: наличие, полная стоимость и порядок оплаты."
        },
        {
          "title": "Подтвердите и отдыхайте",
          "text": "Оплатите, как договорились, и получите детали подачи или бронирования."
        }
      ],
      "priceNote": "Стартовые цены указаны в USD за описанный вариант. Итоговую цену и сумму к оплате в сумах мы подтверждаем до оплаты. Дополнительные услуги рассчитываются отдельно.",
      "paymentNote": "На этом сайте оплата не принимается. Ваша заявка — не подтверждённое бронирование.",
      "customTitle": "Нужно что-то другое?",
      "customText": "Большая группа, другой маршрут или особое пожелание? Расскажите о планах, и мы подберём варианты.",
      "customCta": "Запросить индивидуальный расчёт",
      "restaurantTitle": "Столик на вечер",
      "restaurantText": "Расскажите, какую кухню, время и количество гостей вы хотите. Мы проверим наличие мест и условия брони.",
      "restaurantCta": "Забронировать столик",
      "emptyCategory": "В этой категории для вашего отеля пока нет услуг."
    },
    "offers": [
      {
        "id": "tashkent-private-guide",
        "category": "tours",
        "featured": true,
        "title": "Ташкент с местным гидом",
        "eyebrow": "ЧАСТНАЯ ЭКСКУРСИЯ · ТАШКЕНТ",
        "summary": "Превратите прогулку по городу в истории, которые захочется увезти с собой. Расскажите, что вам интересно, и мы подберём экскурсию под ваши планы.",
        "description": "Интересует старый город, местная кухня или повседневная жизнь? Попросите маршрут по вашим интересам. Гида, язык, длительность и размер группы мы подтверждаем до оплаты.",
        "price": {
          "mode": "from",
          "amount": 120,
          "currency": "USD",
          "unit": "за согласованную экскурсию",
          "billingUnit": "excursion"
        },
        "image": "assets/tashkent-tv-tower.jpg",
        "imageAlt": "Ташкент с высоты на закате, над городом — телебашня",
        "imageFit": "cover",
        "imageCaption": "Ташкент для вдохновения. Маршрут согласуется отдельно.",
        "facts": [
          "Частный гид",
          "Язык согласуем заранее",
          "Маршрут под ваши интересы"
        ],
        "includes": [
          "Гид на одну согласованную экскурсию"
        ],
        "extras": [
          "Транспорт, входные билеты и питание, если они не включены в ваш расчёт"
        ],
        "confirmBeforePayment": [
          "Наличие гида и язык",
          "Длительность экскурсии, маршрут и место встречи",
          "Размер группы и итоговая сумма"
        ],
        "requestProfile": "guide",
        "cta": "Заказать экскурсию"
      },
      {
        "id": "tashkent-mountains-base",
        "category": "tours",
        "featured": true,
        "title": "Из города — к горным видам",
        "eyebrow": "ДЕНЬ В ГОРАХ · ИЗ ТАШКЕНТА",
        "summary": "Свежий воздух, простор и смена ритма. Спросите нас о маршруте в сторону Чимгана, Чарвака или Амирсоя.",
        "description": "Расскажите, что вам ближе: горные пейзажи, остановка у озера или визит на курорт. Мы подтвердим маршрут и автомобиль для вашего дня за городом. Стартовая цена — за один согласованный маршрут, а не за все направления сразу.",
        "price": {
          "mode": "from",
          "amount": 160,
          "currency": "USD",
          "unit": "за автомобиль · согласованный маршрут на день",
          "billingUnit": "vehicle_route"
        },
        "image": "assets/charvak-lake.jpg",
        "imageAlt": "Бирюзовое Чарвакское водохранилище у подножия гор недалеко от Ташкента",
        "imageFit": "cover",
        "imageCaption": "Чарвак для вдохновения. Остановки зависят от подтверждённого маршрута.",
        "facts": [
          "Выезд из Ташкента",
          "Частный автомобиль с водителем",
          "Маршрут согласуем с вами"
        ],
        "includes": [
          "Частный автомобиль с водителем по согласованному горному маршруту"
        ],
        "extras": [
          "Канатные дороги, входные билеты, гид и питание, если они не включены в ваш расчёт"
        ],
        "confirmBeforePayment": [
          "Точный маршрут, остановки и возвращение",
          "Расписание, состояние дорог и погода",
          "Автомобиль, число пассажиров и багаж",
          "Полная цена, включая парковку и дорожные сборы"
        ],
        "requestProfile": "mountains",
        "cta": "Спланировать день в горах"
      },
      {
        "id": "tashkent-city-car",
        "category": "tours",
        "featured": true,
        "title": "Свой темп. Свой день в городе.",
        "eyebrow": "АВТОМОБИЛЬ С ВОДИТЕЛЕМ · ТАШКЕНТ",
        "summary": "Найдите время для мест, которые хотите увидеть. Частный автомобиль с водителем отвезёт вас между согласованными точками города.",
        "description": "Спланируйте день по своим интересам, не заказывая новую машину на каждой остановке. Это услуга «автомобиль с водителем» по Ташкенту в согласованное время 09:00–18:00. Экскурсионного гида можно рассчитать отдельно.",
        "price": {
          "mode": "from",
          "amount": 140,
          "currency": "USD",
          "unit": "за автомобиль · 09:00–18:00",
          "billingUnit": "vehicle_day"
        },
        "image": "assets/tashkent-chorsu-bazaar.jpg",
        "imageAlt": "Голубой купол базара Чорсу в Ташкенте с покупателями у входа",
        "imageFit": "cover",
        "imageCaption": "Город для вдохновения. Остановки согласуются до подтверждения.",
        "facts": [
          "Автомобиль и водитель",
          "09:00–18:00",
          "Топливо и парковка включены"
        ],
        "includes": [
          "Частный автомобиль с водителем по Ташкенту с 09:00 до 18:00",
          "Топливо и парковка по согласованной городской программе"
        ],
        "extras": [
          "Профессиональный гид, входные билеты и питание",
          "Дополнительные часы или поездки за пределы согласованной зоны"
        ],
        "confirmBeforePayment": [
          "Дата, место подачи и маршрут по городу",
          "Автомобиль и число пассажиров",
          "Дополнительные часы и их стоимость"
        ],
        "requestProfile": "city",
        "cta": "Спланировать день в городе"
      },
      {
        "id": "tashkent-airport-sedan",
        "category": "transport",
        "featured": true,
        "title": "Ваш трансфер из аэропорта — организован",
        "eyebrow": "ТРАНСФЕР ИЗ АЭРОПОРТА · ДО 3 ПАССАЖИРОВ",
        "summary": "Начните или завершите поездку в Ташкент частным трансфером между аэропортом и отелем.",
        "description": "Сообщите рейс, направление и данные о багаже. Мы подтвердим место встречи и автомобиль, чтобы вы знали, чего ожидать. Нужна встреча с табличкой? Выберите отдельный вариант «встреча с табличкой».",
        "price": {
          "mode": "from",
          "amount": 30,
          "currency": "USD",
          "unit": "за автомобиль · в одну сторону",
          "billingUnit": "vehicle_one_way"
        },
        "image": "assets/airport-sedan.jpg",
        "imageAlt": "Седан из каталога автомобилей поставщика",
        "imageFit": "contain",
        "imageCaption": "Пример автомобиля; конкретная машина подтверждается отдельно.",
        "facts": [
          "Частный седан",
          "До 3 пассажиров",
          "Аэропорт ↔ отель в Ташкенте"
        ],
        "includes": [
          "Один частный трансфер из аэропорта в подтверждённом направлении"
        ],
        "extras": [
          "Дополнительные остановки, ожидание и особые пожелания — по расчёту",
          "Встреча с табличкой — отдельный вариант"
        ],
        "confirmBeforePayment": [
          "Рейс, дата и время подачи",
          "Число пассажиров и багаж",
          "Место встречи, условия ожидания и полная цена"
        ],
        "requestProfile": "airport",
        "cta": "Заказать трансфер"
      },
      {
        "id": "tashkent-airport-minivan",
        "category": "transport",
        "featured": true,
        "title": "Прилетели вместе — едете вместе",
        "eyebrow": "МИНИВЭН ИЗ АЭРОПОРТА · ДО 5 ПАССАЖИРОВ",
        "summary": "Один частный трансфер для семьи или небольшой группы. Расскажите, сколько человек и сумок едет.",
        "description": "Вся группа едет вместе между аэропортом Ташкента и отелем. Одно только число пассажиров не гарантирует место для багажа: перед подтверждением автомобиля мы проверяем и то, и другое.",
        "price": {
          "mode": "from",
          "amount": 40,
          "currency": "USD",
          "unit": "за автомобиль · в одну сторону",
          "billingUnit": "vehicle_one_way"
        },
        "image": "assets/family-minivan.jpg",
        "imageAlt": "Минивэн Kia Carnival из каталога поставщика",
        "imageFit": "contain",
        "imageCaption": "Пример автомобиля; модель и вместимость багажа подтверждаются.",
        "facts": [
          "Частный минивэн",
          "До 5 пассажиров",
          "Сначала проверяем место для багажа"
        ],
        "includes": [
          "Один частный трансфер из аэропорта в подтверждённом направлении"
        ],
        "extras": [
          "Дополнительные остановки, ожидание и детские кресла — при наличии и по расчёту",
          "Встреча с табличкой — отдельный вариант"
        ],
        "confirmBeforePayment": [
          "Рейс, направление и время подачи",
          "Пассажиры, багаж и запрос детского кресла",
          "Автомобиль, условия ожидания и итоговая цена"
        ],
        "requestProfile": "airport",
        "cta": "Заказать минивэн"
      },
      {
        "id": "tashkent-samarkand-one-way",
        "category": "tours",
        "featured": true,
        "title": "Следующая остановка: Самарканд",
        "eyebrow": "ТАШКЕНТ → САМАРКАНД · В ОДНУ СТОРОНУ",
        "summary": "Продолжите путешествие без хлопот — с частным водителем. Место подачи и назначение согласуем с вами.",
        "description": "Готовы к следующей части поездки? Пришлите адрес подачи в Ташкенте и адрес назначения в Самарканде. Это междугородний трансфер, а не экскурсия и не поездка туда-обратно.",
        "price": {
          "mode": "from",
          "amount": 200,
          "currency": "USD",
          "unit": "за автомобиль · в одну сторону",
          "billingUnit": "vehicle_one_way"
        },
        "image": "assets/samarkand-registan-square.jpg",
        "imageAlt": "Три медресе площади Регистан в Самарканде под ясным небом",
        "imageFit": "cover",
        "imageCaption": "Направление для вдохновения. Вход на Регистан и экскурсии не включены.",
        "facts": [
          "Частный водитель",
          "Подача в Ташкенте",
          "Высадка в Самарканде"
        ],
        "includes": [
          "Один частный трансфер из Ташкента до согласованного адреса в Самарканде"
        ],
        "extras": [
          "Экскурсии, входные билеты, гид, питание и обратная дорога",
          "Незапланированные объезды или дополнительные остановки"
        ],
        "confirmBeforePayment": [
          "Адреса подачи и высадки, дата и время",
          "Автомобиль, багаж и число пассажиров",
          "Согласованные остановки и полная цена"
        ],
        "requestProfile": "intercity",
        "cta": "Заказать трансфер в Самарканд"
      },
      {
        "id": "tashkent-airport-welcome",
        "category": "transport",
        "featured": false,
        "title": "Встреча с табличкой в Ташкенте",
        "eyebrow": "ПРИЛЁТ · ВСТРЕЧА С ТАБЛИЧКОЙ",
        "summary": "Хотите, чтобы вас встретили с вашим именем? Закажите встречу и частный трансфер до отеля в Ташкенте.",
        "description": "Наша команда до оплаты подтверждает удобное место встречи, детали прилёта и автомобиль. Это отдельный пакет трансфера; цена не прибавляется к стоимости седана или минивэна.",
        "price": {
          "mode": "from",
          "amount": 45,
          "currency": "USD",
          "unit": "за автомобиль · пакет по прилёту",
          "billingUnit": "vehicle_arrival_package"
        },
        "image": "assets/family-minivan.jpg",
        "imageAlt": "Иллюстративный автомобиль из каталога поставщика",
        "imageFit": "contain",
        "imageCaption": "Иллюстративный автомобиль; этот пакет не гарантирует минивэн.",
        "facts": [
          "Встреча с табличкой",
          "Аэропорт → отель в Ташкенте",
          "Место встречи подтверждается"
        ],
        "includes": [
          "Встреча с табличкой в согласованном доступном месте",
          "Частный трансфер до согласованного отеля в Ташкенте"
        ],
        "extras": [
          "Дополнительные остановки, ожидание и прочее — по расчёту"
        ],
        "confirmBeforePayment": [
          "Наличие у поставщика, автомобиль и вместимость",
          "Рейс и доступное место встречи",
          "Условия ожидания и итоговая цена"
        ],
        "requestProfile": "airport_arrival",
        "cta": "Заказать встречу с трансфером"
      },
      {
        "id": "ticket-assistance",
        "category": "tickets",
        "featured": true,
        "title": "Куда дальше?",
        "eyebrow": "АВИА · Ж/Д · АВТОБУСЫ",
        "summary": "Сообщите маршрут и дату поездки. Мы найдём доступные варианты и поможем купить подходящий билет.",
        "description": "Единой цены на все поездки нет. Мы проверяем наличие и присылаем полный расчёт, включая сервисный сбор, до вашего решения. Вы платите только после согласия с доступным вариантом и его условиями бронирования.",
        "price": {
          "mode": "quote",
          "amount": null,
          "currency": null,
          "unit": "Полная цена подтверждается до оплаты",
          "billingUnit": null
        },
        "image": null,
        "imageAlt": null,
        "imageFit": null,
        "imageCaption": null,
        "facts": [
          "Самолёт, поезд или автобус",
          "Варианты по вашему маршруту",
          "Полный расчёт до оплаты"
        ],
        "includes": [
          "Помощь в поиске доступных вариантов",
          "Помощь с бронированием выбранного варианта"
        ],
        "extras": [
          "Стоимость билета и сервисный сбор входят в ваш индивидуальный расчёт",
          "Изменения, отмены и возвраты зависят от правил выбранного билета"
        ],
        "confirmBeforePayment": [
          "Маршрут, дата, наличие и данные пассажиров",
          "Тариф, багаж (где применимо), сервисный сбор и итог",
          "Ожидаемое время выдачи билета и условия изменения/возврата"
        ],
        "timing": "Мы стараемся выписать билет в течение 15–30 минут после подтверждения оплаты, когда места и данные пассажиров проверены. Ожидаемые сроки мы подтвердим до оплаты.",
        "requestProfile": "tickets",
        "cta": "Найти билет"
      }
    ],
    "form": {
      "title": "Давайте уточним детали",
      "intro": "Расскажите о планах. Наша команда свяжется с вами, чтобы подтвердить наличие и полную стоимость.",
      "nameLabel": "Ваше имя",
      "contactLabel": "Как с вами связаться",
      "contactPlaceholder": "Телефон с кодом страны, Telegram @username или email",
      "dateLabel": "Желаемая дата",
      "timeLabel": "Желаемое время",
      "countLabel": "Количество человек",
      "noteLabel": "Что-то ещё? (необязательно)",
      "submit": "Отправить заявку",
      "sending": "Отправляем заявку…",
      "back": "Назад к услуге",
      "priceLabel": "Стартовая цена — не итоговая сумма",
      "quoteLabel": "Индивидуальный расчёт — оплаты сейчас нет",
      "privacy": "Мы используем ваше имя, контакт и заявку только для организации услуги. Не вводите здесь паспортные или карточные данные.",
      "payment": "Отправка формы ничего не списывает и не подтверждает бронирование.",
      "successTitle": "Ваша заявка принята.",
      "successText": "Сохраните номер заявки. Наша команда свяжется с вами по указанным данным, чтобы подтвердить наличие, полную стоимость и порядок оплаты.",
      "networkError": "Мы не смогли подтвердить получение заявки. Данные сохранены здесь — попробуйте ещё раз.",
      "rateLimitError": "Недавно было отправлено несколько заявок. Подождите несколько минут и попробуйте снова.",
      "inactiveRoom": "Эта ссылка комнаты недоступна. Попросите в отеле актуальный QR-код MehmonGo.",
      "helpHint": "Если нужна помощь со связью с MehmonGo, обратитесь на ресепшен отеля."
    },
    "faq": [
      {
        "question": "Оплата происходит на этом сайте?",
        "answer": "Нет. Сначала отправьте заявку. Наша команда подтвердит наличие, итоговую сумму и порядок оплаты. Ресепшен вашего отеля может принять оплату по согласованной схеме."
      },
      {
        "question": "Цена указана за человека?",
        "answer": "Частные поездки рассчитаны за автомобиль для указанного варианта. Цена гида — за согласованную экскурсию. Размер группы и дополнительные расходы мы подтверждаем до оплаты."
      },
      {
        "question": "Бронирование подтверждено, когда я отправляю заявку?",
        "answer": "Пока нет. Мы свяжемся с вами, чтобы согласовать детали и объяснить, как подтвердить бронирование."
      },
      {
        "question": "Можно изменить или отменить?",
        "answer": "Условия зависят от услуги и поставщика. Условия изменения или отмены мы объясним до оплаты."
      }
    ]
  },
  "uz": {
    "version": "mehmongo-tashkent-2026-09-05-final",
    "locale": "uz",
    "departureCity": "Toshkent",
    "currency": "USD",
    "page": {
      "eyebrow": "SIZNING DAM OLISHINGIZ, SIZNING REJALARINGIZ",
      "title": "Ozgina reja. Koʻproq Toshkent.",
      "intro": "Mahalliy gid, togʻlarga sayohat yoki keyingi safaringiz. Kerakli xizmatni tanlang, tafsilotlarni MehmonGo hal qiladi.",
      "primaryCta": "Xizmatlarni koʻrish",
      "trustItems": [
        "Roʻyxatdan oʻtish shart emas",
        "Narx toʻlovdan oldin tasdiqlanadi",
        "Jamoamiz yordami"
      ],
      "sectionTitle": "Dam olishingizni nima yaxshilaydi?",
      "sectionIntro": "Gʻoyadan boshlang. Tafsilotlarda biz yordam beramiz.",
      "filters": [
        {
          "id": "all",
          "label": "Barcha xizmatlar"
        },
        {
          "id": "tours",
          "label": "Sayohatlar va gidlar"
        },
        {
          "id": "transport",
          "label": "Shaxsiy transport"
        },
        {
          "id": "tickets",
          "label": "Samolyot, poyezd va avtobus"
        }
      ],
      "stepsTitle": "Gʻoyadan rejagacha",
      "steps": [
        {
          "title": "Xizmatni tanlang",
          "text": "Safar, sayohat yoki chipta boʻyicha soʻrov yuboring."
        },
        {
          "title": "Biz tafsilotlarni tasdiqlaymiz",
          "text": "Jamoamiz siz bilan bogʻlanib, mavjudlik, toʻliq narx va toʻlov tartibini aytadi."
        },
        {
          "title": "Tasdiqlang va bahra oling",
          "text": "Kelishilganidek toʻlang va olib ketish yoki bron tafsilotlarini oling."
        }
      ],
      "priceNote": "Boshlangʻich narxlar tavsiflangan variant uchun USD da koʻrsatilgan. Yakuniy narx va soʻmda toʻlanadigan summani toʻlovdan oldin tasdiqlaymiz. Qoʻshimcha xizmatlar alohida hisoblanadi.",
      "paymentNote": "Bu saytda toʻlov qabul qilinmaydi. Soʻrovingiz tasdiqlangan bron emas.",
      "customTitle": "Boshqa narsa kerakmi?",
      "customText": "Katta guruh, boshqa yoʻnalish yoki maxsus istakmi? Rejalaringizni ayting, biz variantlarni koʻrib chiqamiz.",
      "customCta": "Alohida narx soʻrash",
      "restaurantTitle": "Kechki ovqat uchun stol",
      "restaurantText": "Qanday taom, vaqt va necha kishi ekanini ayting. Biz boʻsh joy va bron shartlarini tekshiramiz.",
      "restaurantCta": "Restoranda stol band qilish",
      "emptyCategory": "Hozircha bu toifada mehmonxonangiz uchun xizmatlar yoʻq."
    },
    "offers": [
      {
        "id": "tashkent-private-guide",
        "category": "tours",
        "featured": true,
        "title": "Toshkentni mahalliy gid bilan koʻring",
        "eyebrow": "SHAXSIY EKSKURSIYA · TOSHKENT",
        "summary": "Shahar boʻylab sayrni esda qoladigan hikoyalarga aylantiring. Sizni nima qiziqtirishini ayting, biz ekskursiyani rejalaringizga moslaymiz.",
        "description": "Eski shahar, mahalliy taomlar yoki kundalik hayot qiziqtiradimi? Qiziqishlaringizga mos marshrut soʻrang. Gid, til, davomiylik va guruh hajmini toʻlovdan oldin tasdiqlaymiz.",
        "price": {
          "mode": "from",
          "amount": 120,
          "currency": "USD",
          "unit": "kelishilgan ekskursiya uchun",
          "billingUnit": "excursion"
        },
        "image": "assets/tashkent-tv-tower.jpg",
        "imageAlt": "Quyosh botishida yuqoridan koʻringan Toshkent va shahar uzra teleminora",
        "imageFit": "cover",
        "imageCaption": "Toshkent ilhomi. Marshrutingiz alohida kelishiladi.",
        "facts": [
          "Shaxsiy gid",
          "Til oldindan kelishiladi",
          "Marshrut qiziqishlaringizga mos"
        ],
        "includes": [
          "Bitta kelishilgan ekskursiya uchun gid"
        ],
        "extras": [
          "Transport, kirish chiptalari va ovqat, agar hisobingizga kiritilmagan boʻlsa"
        ],
        "confirmBeforePayment": [
          "Gid mavjudligi va tili",
          "Ekskursiya davomiyligi, marshrut va uchrashuv joyi",
          "Guruh hajmi va yakuniy summa"
        ],
        "requestProfile": "guide",
        "cta": "Ekskursiyaga soʻrov yuborish"
      },
      {
        "id": "tashkent-mountains-base",
        "category": "tours",
        "featured": true,
        "title": "Shahardan togʻ manzaralariga",
        "eyebrow": "TOGʻLARGA BIR KUNLIK SAYOHAT · TOSHKENTDAN",
        "summary": "Toza havo, keng manzaralar va boshqa ritm. Chimyon, Chorvoq yoki Amirsoy tomon marshrut haqida soʻrang.",
        "description": "Togʻ manzaralari, koʻl boʻyida toʻxtash yoki kurortga tashrif — qaysi biri sizga yoqishini ayting. Toshkentdan bir kunlik sayohatingiz uchun marshrut va avtomobilni tasdiqlaymiz. Boshlangʻich narx bitta kelishilgan marshrut uchun, barcha yoʻnalishlar birgalikda emas.",
        "price": {
          "mode": "from",
          "amount": 160,
          "currency": "USD",
          "unit": "avtomobil uchun · kelishilgan bir kunlik marshrut",
          "billingUnit": "vehicle_route"
        },
        "image": "assets/charvak-lake.jpg",
        "imageAlt": "Toshkent yaqinidagi togʻlar ostidagi moviy Chorvoq suv ombori",
        "imageFit": "cover",
        "imageCaption": "Chorvoq ilhomi. Toʻxtash joylari tasdiqlangan marshrutga bogʻliq.",
        "facts": [
          "Toshkentdan joʻnash",
          "Haydovchili shaxsiy avtomobil",
          "Marshrut siz bilan tasdiqlanadi"
        ],
        "includes": [
          "Kelishilgan togʻ marshruti uchun haydovchili shaxsiy avtomobil"
        ],
        "extras": [
          "Arqon yoʻllar, kirish chiptalari, gid va ovqat, agar hisobingizga kiritilmagan boʻlsa"
        ],
        "confirmBeforePayment": [
          "Aniq marshrut, toʻxtash joylari va qaytish tartibi",
          "Jadval, yoʻl va ob-havo sharoiti",
          "Avtomobil, yoʻlovchi va yuk sigʻimi",
          "Toʻliq narx, shu jumladan avtoturargoh va yoʻl toʻlovlari"
        ],
        "requestProfile": "mountains",
        "cta": "Togʻ kunimni rejalashtirish"
      },
      {
        "id": "tashkent-city-car",
        "category": "tours",
        "featured": true,
        "title": "Oʻz tempingiz. Oʻz shahar kuningiz.",
        "eyebrow": "HAYDOVCHILI SHAXSIY AVTOMOBIL · TOSHKENT",
        "summary": "Koʻrmoqchi boʻlgan joylaringizga vaqt ajrating. Haydovchili shaxsiy avtomobil sizni kelishilgan shahar nuqtalari orasida olib yuradi.",
        "description": "Har bir toʻxtashda yangi transport qidirmasdan, kunni qiziqishlaringiz boʻyicha rejalashtiring. Bu Toshkent ichida kelishilgan 09:00–18:00 jadvalidagi haydovchili avtomobil xizmati. Ekskursiya gidi alohida hisoblanishi mumkin.",
        "price": {
          "mode": "from",
          "amount": 140,
          "currency": "USD",
          "unit": "avtomobil uchun · 09:00–18:00",
          "billingUnit": "vehicle_day"
        },
        "image": "assets/tashkent-chorsu-bazaar.jpg",
        "imageAlt": "Toshkentdagi Chorsu bozorining moviy gumbazi va kiraverishdagi xaridorlar",
        "imageFit": "cover",
        "imageCaption": "Shahar ilhomi. Toʻxtash joylari tasdiqlashdan oldin kelishiladi.",
        "facts": [
          "Avtomobil va haydovchi",
          "09:00–18:00",
          "Yoqilgʻi va avtoturargoh narxga kiradi"
        ],
        "includes": [
          "Toshkent ichida 09:00–18:00 uchun haydovchili shaxsiy avtomobil",
          "Kelishilgan shahar xizmati uchun yoqilgʻi va avtoturargoh"
        ],
        "extras": [
          "Professional gid, kirish chiptalari va ovqat",
          "Qoʻshimcha soatlar yoki kelishilgan hududdan tashqari safarlar"
        ],
        "confirmBeforePayment": [
          "Sana, olib ketish joyi va shahar marshruti",
          "Avtomobil va yoʻlovchilar soni",
          "Qoʻshimcha soatlar va ularning narxi"
        ],
        "requestProfile": "city",
        "cta": "Shahar kunimni rejalashtirish"
      },
      {
        "id": "tashkent-airport-sedan",
        "category": "transport",
        "featured": true,
        "title": "Aeroport transferingiz tayyor",
        "eyebrow": "AEROPORT TRANSFERI · 3 YOʻLOVCHIGACHA",
        "summary": "Toshkentdagi safaringizni aeroport va mehmonxona orasidagi shaxsiy transfer bilan boshlang yoki yakunlang.",
        "description": "Reys, yoʻnalish va yuk haqida maʼlumot bering. Nimani kutishingizni bilishingiz uchun uchrashuv joyi va avtomobilni tasdiqlaymiz. Ismingiz yozilgan taxtacha bilan kutib olish kerakmi? Alohida kutib olish variantini tanlang.",
        "price": {
          "mode": "from",
          "amount": 30,
          "currency": "USD",
          "unit": "avtomobil uchun · bir tomonga",
          "billingUnit": "vehicle_one_way"
        },
        "image": "assets/airport-sedan.jpg",
        "imageAlt": "Yetkazib beruvchi avtomobillar katalogidagi sedan",
        "imageFit": "contain",
        "imageCaption": "Avtomobil namunasi; aniq mashina alohida tasdiqlanadi.",
        "facts": [
          "Shaxsiy sedan",
          "3 yoʻlovchigacha",
          "Aeroport ↔ Toshkentdagi mehmonxona"
        ],
        "includes": [
          "Tasdiqlangan yoʻnalishda bitta shaxsiy aeroport transferi"
        ],
        "extras": [
          "Qoʻshimcha toʻxtashlar, kutish va maxsus istaklar — hisob boʻyicha",
          "Taxtacha bilan kutib olish — alohida variant"
        ],
        "confirmBeforePayment": [
          "Reys, sana va olib ketish vaqti",
          "Yoʻlovchilar va yuk sigʻimi",
          "Uchrashuv joyi, kutish shartlari va toʻliq narx"
        ],
        "requestProfile": "airport",
        "cta": "Aeroport transferini buyurtma qilish"
      },
      {
        "id": "tashkent-airport-minivan",
        "category": "transport",
        "featured": true,
        "title": "Birga keling, birga boring",
        "eyebrow": "AEROPORT MINIVENI · 5 YOʻLOVCHIGACHA",
        "summary": "Oilangiz yoki kichik guruhingiz uchun bitta shaxsiy transfer. Necha kishi va necha sumka borishini ayting.",
        "description": "Toshkent aeroporti va mehmonxona orasida guruhingiz birga boradi. Yoʻlovchilar sonining oʻzi yuk uchun joyni kafolatlamaydi: avtomobilni tasdiqlashdan oldin ikkalasini ham tekshiramiz.",
        "price": {
          "mode": "from",
          "amount": 40,
          "currency": "USD",
          "unit": "avtomobil uchun · bir tomonga",
          "billingUnit": "vehicle_one_way"
        },
        "image": "assets/family-minivan.jpg",
        "imageAlt": "Yetkazib beruvchi katalogidagi Kia Carnival miniveni",
        "imageFit": "contain",
        "imageCaption": "Avtomobil namunasi; model va yuk sigʻimi tasdiqlanadi.",
        "facts": [
          "Shaxsiy miniven",
          "5 yoʻlovchigacha",
          "Avval yuk uchun joy tekshiriladi"
        ],
        "includes": [
          "Tasdiqlangan yoʻnalishda bitta shaxsiy aeroport transferi"
        ],
        "extras": [
          "Qoʻshimcha toʻxtashlar, kutish va bolalar oʻrindiqlari — mavjud boʻlsa va hisob boʻyicha",
          "Taxtacha bilan kutib olish — alohida variant"
        ],
        "confirmBeforePayment": [
          "Reys, yoʻnalish va olib ketish vaqti",
          "Yoʻlovchilar, sumkalar va bolalar oʻrindigʻi soʻrovi",
          "Avtomobil, kutish shartlari va yakuniy narx"
        ],
        "requestProfile": "airport",
        "cta": "Miniven buyurtma qilish"
      },
      {
        "id": "tashkent-samarkand-one-way",
        "category": "tours",
        "featured": true,
        "title": "Keyingi bekat: Samarqand",
        "eyebrow": "TOSHKENT → SAMARQAND · BIR TOMONGA",
        "summary": "Shaxsiy haydovchi bilan keyingi safaringizni oson qiling. Olib ketish joyi va manzilni siz bilan kelishamiz.",
        "description": "Sayohatning keyingi qismiga tayyormisiz? Toshkentdagi olib ketish manzili va Samarqanddagi manzilni yuboring. Bu shaharlararo transfer, ekskursiya yoki qaytish safari emas.",
        "price": {
          "mode": "from",
          "amount": 200,
          "currency": "USD",
          "unit": "avtomobil uchun · bir tomonga",
          "billingUnit": "vehicle_one_way"
        },
        "image": "assets/samarkand-registan-square.jpg",
        "imageAlt": "Samarqanddagi Registon maydonining uchta madrasasi ochiq osmon ostida",
        "imageFit": "cover",
        "imageCaption": "Manzil ilhomi. Registonga kirish va ekskursiya narxga kirmaydi.",
        "facts": [
          "Shaxsiy haydovchi",
          "Toshkentdan olib ketish",
          "Samarqandda tushirish"
        ],
        "includes": [
          "Toshkentdan Samarqanddagi kelishilgan manzilgacha bitta shaxsiy transfer"
        ],
        "extras": [
          "Ekskursiya, kirish chiptalari, gid, ovqat va qaytish yoʻli",
          "Rejalashtirilmagan aylanma yoʻllar yoki qoʻshimcha toʻxtashlar"
        ],
        "confirmBeforePayment": [
          "Olib ketish va tushirish manzillari, sana va vaqt",
          "Avtomobil, yuk va yoʻlovchilar sigʻimi",
          "Kelishilgan toʻxtashlar va toʻliq narx"
        ],
        "requestProfile": "intercity",
        "cta": "Samarqandga transfer buyurtma qilish"
      },
      {
        "id": "tashkent-airport-welcome",
        "category": "transport",
        "featured": false,
        "title": "Toshkentda taxtacha bilan kutib olish",
        "eyebrow": "AEROPORTGA KELISH · KUTIB OLISH",
        "summary": "Sizni ismingiz bilan kutib olishlarini xohlaysizmi? Kutib olish va Toshkentdagi mehmonxonangizgacha shaxsiy transfer soʻrang.",
        "description": "Jamoamiz toʻlovdan oldin qulay uchrashuv joyi, kelish tafsilotlari va avtomobilni tasdiqlaydi. Bu alohida transfer paketi; narx sedan yoki miniven narxiga qoʻshimcha emas.",
        "price": {
          "mode": "from",
          "amount": 45,
          "currency": "USD",
          "unit": "avtomobil uchun · kelish paketi",
          "billingUnit": "vehicle_arrival_package"
        },
        "image": "assets/family-minivan.jpg",
        "imageAlt": "Yetkazib beruvchi katalogidagi namunaviy avtomobil",
        "imageFit": "contain",
        "imageCaption": "Namunaviy avtomobil; bu paket minivenni kafolatlamaydi.",
        "facts": [
          "Taxtacha bilan kutib olish",
          "Aeroport → Toshkentdagi mehmonxona",
          "Uchrashuv joyi tasdiqlanadi"
        ],
        "includes": [
          "Kelishilgan qulay joyda ism yozilgan taxtacha bilan kutib olish",
          "Toshkentdagi kelishilgan mehmonxonagacha shaxsiy transfer"
        ],
        "extras": [
          "Qoʻshimcha toʻxtashlar, kutish yoki boshqa qoʻshimchalar — hisob boʻyicha"
        ],
        "confirmBeforePayment": [
          "Yetkazib beruvchi mavjudligi, avtomobil va sigʻim",
          "Reys va qulay uchrashuv joyi",
          "Kutish shartlari va umumiy narx"
        ],
        "requestProfile": "airport_arrival",
        "cta": "Kutib olish bilan transfer soʻrash"
      },
      {
        "id": "ticket-assistance",
        "category": "tickets",
        "featured": true,
        "title": "Keyin qayerga?",
        "eyebrow": "SAMOLYOT · POYEZD · AVTOBUS",
        "summary": "Yoʻnalish va sayohat sanasini ayting. Mavjud variantlarni qidirib, rejalaringizga mos chiptani sotib olishga yordam beramiz.",
        "description": "Har bir safar uchun yagona narx yoʻq. Mavjudlikni tekshirib, qaror qilishingizdan oldin xizmat haqi bilan toʻliq hisobni yuboramiz. Faqat mavjud variant va uning bron shartlariga rozi boʻlgach toʻlaysiz.",
        "price": {
          "mode": "quote",
          "amount": null,
          "currency": null,
          "unit": "Toʻliq narx toʻlovdan oldin tasdiqlanadi",
          "billingUnit": null
        },
        "image": null,
        "imageAlt": null,
        "imageFit": null,
        "imageCaption": null,
        "facts": [
          "Samolyot, poyezd yoki avtobus",
          "Yoʻnalishingiz boʻyicha variantlar",
          "Toʻlovdan oldin toʻliq hisob"
        ],
        "includes": [
          "Mavjud variantlarni qidirishda yordam",
          "Siz maʼqullagan variantni bron qilishda yordam"
        ],
        "extras": [
          "Chipta narxi va xizmat haqi alohida hisobingizga kiradi",
          "Oʻzgartirish, bekor qilish va qaytarish tanlangan chipta qoidalariga bogʻliq"
        ],
        "confirmBeforePayment": [
          "Yoʻnalish, sana, mavjudlik va yoʻlovchi maʼlumotlari",
          "Tarif, kerak boʻlsa yuk, xizmat haqi va jami",
          "Chipta berishning kutilayotgan vaqti va oʻzgartirish/qaytarish shartlari"
        ],
        "timing": "Joylar va yoʻlovchi maʼlumotlari tekshirilgach, toʻlov tasdiqlanganidan keyin 15–30 daqiqa ichida chiptani rasmiylashtirishga harakat qilamiz. Kutilayotgan muddatni toʻlovdan oldin tasdiqlaymiz.",
        "requestProfile": "tickets",
        "cta": "Chiptamni topish"
      }
    ],
    "form": {
      "title": "Keling, tafsilotlarni kelishamiz",
      "intro": "Rejalaringizni ayting. Jamoamiz mavjudlik va toʻliq narxni tasdiqlash uchun siz bilan bogʻlanadi.",
      "nameLabel": "Ismingiz",
      "contactLabel": "Siz bilan bogʻlanish usuli",
      "contactPlaceholder": "Davlat kodi bilan telefon, Telegram @username yoki email",
      "dateLabel": "Qulay sana",
      "timeLabel": "Qulay vaqt",
      "countLabel": "Sayohatchilar soni",
      "noteLabel": "Yana biror narsa? (ixtiyoriy)",
      "submit": "Soʻrovimni yuborish",
      "sending": "Soʻrovingiz yuborilmoqda…",
      "back": "Xizmatga qaytish",
      "priceLabel": "Boshlangʻich narx — yakuniy summa emas",
      "quoteLabel": "Alohida hisob — hozir toʻlov yoʻq",
      "privacy": "Ismingiz, kontaktingiz va soʻrovingizdan faqat xizmatni tashkil qilish uchun foydalanamiz. Bu yerga pasport yoki karta maʼlumotlarini kiritmang.",
      "payment": "Bu formani yuborish sizdan pul yechmaydi va bronni tasdiqlamaydi.",
      "successTitle": "Soʻrovingiz qabul qilindi.",
      "successText": "Soʻrov raqamini saqlab qoʻying. Jamoamiz mavjudlik, toʻliq narx va toʻlov tartibini tasdiqlash uchun siz koʻrsatgan maʼlumotlar orqali bogʻlanadi.",
      "networkError": "Soʻrovingiz qabul qilinganini tasdiqlay olmadik. Maʼlumotlaringiz shu yerda saqlanadi — qayta urinib koʻring.",
      "rateLimitError": "Yaqinda bir nechta soʻrov yuborildi. Bir necha daqiqa kutib, qayta urinib koʻring.",
      "inactiveRoom": "Bu xona havolasi mavjud emas. Mehmonxonadan joriy MehmonGo QR kodini soʻrang.",
      "helpHint": "MehmonGo bilan bogʻlanishda yordam kerak boʻlsa, mehmonxona qabulxonasiga murojaat qiling."
    },
    "faq": [
      {
        "question": "Bu saytda toʻlov qilamanmi?",
        "answer": "Yoʻq. Avval soʻrov yuboring. Jamoamiz mavjudlik, umumiy summa va toʻlov tartibini tasdiqlaydi. Mehmonxona qabulxonasi kelishilgan tartibda toʻlovni qabul qilishi mumkin."
      },
      {
        "question": "Narx bir kishi uchunmi?",
        "answer": "Shaxsiy transport koʻrsatilgan variant uchun avtomobil boʻyicha hisoblanadi. Gid narxi — kelishilgan ekskursiya uchun. Guruh hajmi va qoʻshimcha xarajatlarni toʻlovdan oldin tasdiqlaymiz."
      },
      {
        "question": "Soʻrov yuborganimda bron tasdiqlanadimi?",
        "answer": "Hali yoʻq. Tafsilotlarni kelishish va bronni qanday tasdiqlashni tushuntirish uchun siz bilan bogʻlanamiz."
      },
      {
        "question": "Oʻzgartirish yoki bekor qilish mumkinmi?",
        "answer": "Shartlar xizmat va yetkazib beruvchiga bogʻliq. Oʻzgartirish yoki bekor qilish shartlarini toʻlovdan oldin tushuntiramiz."
      }
    ]
  },
  "zh": {
    "version": "mehmongo-tashkent-2026-09-05-final",
    "locale": "zh",
    "departureCity": "塔什干",
    "currency": "USD",
    "page": {
      "eyebrow": "您的旅程，您做主",
      "title": "稍作规划，尽享塔什干。",
      "intro": "本地向导、山间一日游或下一程出行。选择您需要的服务，让 MehmonGo 为您安排细节。",
      "primaryCta": "浏览服务",
      "trustItems": [
        "无需注册账户",
        "付款前确认价格",
        "我们的团队全程协助"
      ],
      "sectionTitle": "什么能让您的入住更美好？",
      "sectionIntro": "从一个想法开始，细节交给我们。",
      "filters": [
        {
          "id": "all",
          "label": "全部服务"
        },
        {
          "id": "tours",
          "label": "游览与向导"
        },
        {
          "id": "transport",
          "label": "专车接送"
        },
        {
          "id": "tickets",
          "label": "机票、火车票与巴士"
        }
      ],
      "stepsTitle": "从想法到计划",
      "steps": [
        {
          "title": "选择服务",
          "text": "选择一次出行、一段体验或一项票务需求。"
        },
        {
          "title": "我们确认细节",
          "text": "我们的团队将与您联系，告知可用性、全部费用及付款方式。"
        },
        {
          "title": "确认并尽情享受",
          "text": "按约定付款后，即可收到接送或预订详情。"
        }
      ],
      "priceNote": "起价以美元计，对应所述选项。付款前我们将确认最终价格及以乌兹别克苏姆支付的金额。额外服务另行报价。",
      "paymentNote": "本网站不收取任何款项。您的申请不构成已确认的预订。",
      "customTitle": "有其他想法？",
      "customText": "人数较多、路线不同或有特别需求？告诉我们您的计划，我们来为您寻找方案。",
      "customCta": "申请单独报价",
      "restaurantTitle": "为您的晚餐订一张桌",
      "restaurantText": "告诉我们您偏好的菜品、时间和人数。我们将确认空位及预订条件。",
      "restaurantCta": "申请餐厅订座",
      "emptyCategory": "您所在酒店目前没有此类服务。"
    },
    "offers": [
      {
        "id": "tashkent-private-guide",
        "category": "tours",
        "featured": true,
        "title": "跟随本地向导游览塔什干",
        "eyebrow": "私人导览 · 塔什干",
        "summary": "让一次城市漫步，变成值得带回家的故事。告诉我们您的兴趣，我们将按您的计划安排导览。",
        "description": "对老城、本地美食或日常生活感兴趣？可按您的兴趣定制路线。付款前我们会确认向导、语言、时长和人数。",
        "price": {
          "mode": "from",
          "amount": 120,
          "currency": "USD",
          "unit": "每次约定的导览",
          "billingUnit": "excursion"
        },
        "image": "assets/tashkent-tv-tower.jpg",
        "imageAlt": "日落时分从高处俯瞰塔什干，电视塔矗立在城市上方",
        "imageFit": "cover",
        "imageCaption": "塔什干灵感图。您的路线将另行商定。",
        "facts": [
          "私人向导",
          "语言提前商定",
          "路线按您的兴趣定制"
        ],
        "includes": [
          "一次约定导览的向导服务"
        ],
        "extras": [
          "交通、景点门票及餐饮（除非已包含在您的报价中）"
        ],
        "confirmBeforePayment": [
          "向导的可用性及语言",
          "导览时长、路线及集合地点",
          "人数及最终总价"
        ],
        "requestProfile": "guide",
        "cta": "申请此导览"
      },
      {
        "id": "tashkent-mountains-base",
        "category": "tours",
        "featured": true,
        "title": "离开城市，走进山间",
        "eyebrow": "山间一日游 · 从塔什干出发",
        "summary": "清新空气、开阔景色和不一样的节奏。向我们咨询前往奇姆干、恰尔瓦克或阿米尔索伊的路线。",
        "description": "告诉我们您偏好山景、湖畔停留还是度假村之行。我们将为您从塔什干出发的一日游确认路线和车辆。起价仅包含一条约定路线，而非所有目的地。",
        "price": {
          "mode": "from",
          "amount": 160,
          "currency": "USD",
          "unit": "每车 · 约定的一日游路线",
          "billingUnit": "vehicle_route"
        },
        "image": "assets/charvak-lake.jpg",
        "imageAlt": "塔什干附近群山脚下碧绿的恰尔瓦克水库",
        "imageFit": "cover",
        "imageCaption": "恰尔瓦克灵感图。停留地点取决于确认的路线。",
        "facts": [
          "从塔什干出发",
          "私人专车含司机",
          "路线与您共同确认"
        ],
        "includes": [
          "约定山间路线的私人专车及司机"
        ],
        "extras": [
          "缆车、景点门票、向导及餐饮（除非已包含在您的报价中）"
        ],
        "confirmBeforePayment": [
          "具体路线、停留地点及返程安排",
          "行程时间、路况及天气情况",
          "车辆、乘客及行李容量",
          "全部费用，包括停车费或路桥费"
        ],
        "requestProfile": "mountains",
        "cta": "规划我的山间之旅"
      },
      {
        "id": "tashkent-city-car",
        "category": "tours",
        "featured": true,
        "title": "您的节奏，您的城市一日。",
        "eyebrow": "私人专车含司机 · 塔什干",
        "summary": "为您想看的地方留出时间。私人专车和司机带您在约定的市内景点之间往返。",
        "description": "按您的兴趣规划一天，无需在每一站重新叫车。这是塔什干市内的包车服务，服务时间为约定的 09:00–18:00。观光向导可另行报价。",
        "price": {
          "mode": "from",
          "amount": 140,
          "currency": "USD",
          "unit": "每车 · 09:00–18:00",
          "billingUnit": "vehicle_day"
        },
        "image": "assets/tashkent-chorsu-bazaar.jpg",
        "imageAlt": "塔什干楚苏集市的蓝色瓷砖穹顶，入口处有购物的人群",
        "imageFit": "cover",
        "imageCaption": "城市灵感图。停留地点在确认前商定。",
        "facts": [
          "专车及司机",
          "09:00–18:00",
          "含燃油及停车费"
        ],
        "includes": [
          "09:00–18:00 塔什干市内私人专车及司机",
          "约定市内服务的燃油及停车费"
        ],
        "extras": [
          "专业向导、景点门票及餐饮",
          "额外时长或约定区域以外的行程"
        ],
        "confirmBeforePayment": [
          "日期、上车地点及市内行程",
          "车辆及乘客容量",
          "任何额外时长及其费用"
        ],
        "requestProfile": "city",
        "cta": "规划我的城市一日"
      },
      {
        "id": "tashkent-airport-sedan",
        "category": "transport",
        "featured": true,
        "title": "您的机场接送，已安排妥当",
        "eyebrow": "机场接送 · 最多 3 位乘客",
        "summary": "以机场与酒店之间的私人接送，开启或结束您的塔什干之行。",
        "description": "告诉我们您的航班、接送方向和行李情况。我们将确认接机地点和车辆，让您心中有数。需要举牌迎接？请选择单独的举牌接机选项。",
        "price": {
          "mode": "from",
          "amount": 30,
          "currency": "USD",
          "unit": "每车 · 单程",
          "billingUnit": "vehicle_one_way"
        },
        "image": "assets/airport-sedan.jpg",
        "imageAlt": "供应商车辆目录中的轿车",
        "imageFit": "contain",
        "imageCaption": "车辆示例；实际派车另行确认。",
        "facts": [
          "私人轿车",
          "最多 3 位乘客",
          "机场 ↔ 塔什干酒店"
        ],
        "includes": [
          "确认方向的一次私人机场接送"
        ],
        "extras": [
          "额外停靠、等候及特殊需求（如有报价）",
          "举牌接机为单独选项"
        ],
        "confirmBeforePayment": [
          "航班、日期及接送时间",
          "乘客及行李是否合适",
          "接机地点、等候政策及全部费用"
        ],
        "requestProfile": "airport",
        "cta": "安排我的机场接送"
      },
      {
        "id": "tashkent-airport-minivan",
        "category": "transport",
        "featured": true,
        "title": "一同抵达，一同出行",
        "eyebrow": "机场商务车 · 最多 5 位乘客",
        "summary": "为您的家庭或小团队安排一次私人接送。告诉我们出行人数和行李件数。",
        "description": "让您的团队在塔什干机场与酒店之间同车出行。仅凭乘客人数无法保证行李空间：确认车辆前，我们会同时核实两者。",
        "price": {
          "mode": "from",
          "amount": 40,
          "currency": "USD",
          "unit": "每车 · 单程",
          "billingUnit": "vehicle_one_way"
        },
        "image": "assets/family-minivan.jpg",
        "imageAlt": "供应商目录中的起亚嘉华商务车",
        "imageFit": "contain",
        "imageCaption": "车辆示例；车型及行李容量另行确认。",
        "facts": [
          "私人商务车",
          "最多 5 位乘客",
          "先核实行李空间"
        ],
        "includes": [
          "确认方向的一次私人机场接送"
        ],
        "extras": [
          "额外停靠、等候及儿童座椅（如有并报价）",
          "举牌接机为单独选项"
        ],
        "confirmBeforePayment": [
          "航班、方向及接送时间",
          "乘客、行李及儿童座椅需求",
          "车辆、等候政策及最终价格"
        ],
        "requestProfile": "airport",
        "cta": "安排我们的商务车"
      },
      {
        "id": "tashkent-samarkand-one-way",
        "category": "tours",
        "featured": true,
        "title": "下一站：撒马尔罕",
        "eyebrow": "塔什干 → 撒马尔罕 · 单程",
        "summary": "私人司机让您的下一程轻松简单。上车地点和目的地由我们与您共同安排。",
        "description": "准备好开启旅程的下一段了吗？请发送您在塔什干的上车地址和撒马尔罕的目的地。这是一次城际接送，不含观光，也不含返程。",
        "price": {
          "mode": "from",
          "amount": 200,
          "currency": "USD",
          "unit": "每车 · 单程",
          "billingUnit": "vehicle_one_way"
        },
        "image": "assets/samarkand-registan-square.jpg",
        "imageAlt": "晴空下撒马尔罕雷吉斯坦广场的三座经学院",
        "imageFit": "cover",
        "imageCaption": "目的地灵感图。雷吉斯坦门票及观光不包含在内。",
        "facts": [
          "私人司机",
          "塔什干上车",
          "撒马尔罕下车"
        ],
        "includes": [
          "从塔什干到撒马尔罕约定目的地的一次私人接送"
        ],
        "extras": [
          "观光、景点门票、向导、餐饮及返程",
          "计划外绕行或额外停靠"
        ],
        "confirmBeforePayment": [
          "上车及下车地址、日期和时间",
          "车辆、行李及乘客容量",
          "约定的停靠点及全部费用"
        ],
        "requestProfile": "intercity",
        "cta": "安排我的撒马尔罕之行"
      },
      {
        "id": "tashkent-airport-welcome",
        "category": "transport",
        "featured": false,
        "title": "塔什干举牌接机",
        "eyebrow": "机场抵达 · 举牌迎接",
        "summary": "希望有人举着您的名字迎接？申请举牌接机及前往塔什干酒店的私人接送。",
        "description": "付款前，我们的团队将确认便于到达的接机地点、您的抵达信息及车辆。这是一个独立的接送套餐，价格并非轿车或商务车价格的附加项。",
        "price": {
          "mode": "from",
          "amount": 45,
          "currency": "USD",
          "unit": "每车 · 抵达套餐",
          "billingUnit": "vehicle_arrival_package"
        },
        "image": "assets/family-minivan.jpg",
        "imageAlt": "供应商目录中的示意车辆",
        "imageFit": "contain",
        "imageCaption": "示意车辆；此套餐不保证提供商务车。",
        "facts": [
          "举牌迎接",
          "机场 → 塔什干酒店",
          "接机地点已确认"
        ],
        "includes": [
          "在约定的便利地点举牌迎接",
          "前往约定塔什干酒店的私人接送"
        ],
        "extras": [
          "额外停靠、等候或其他附加项（如有报价）"
        ],
        "confirmBeforePayment": [
          "供应商可用性、车辆及容量",
          "航班及便于到达的接机地点",
          "等候条件及总价"
        ],
        "requestProfile": "airport_arrival",
        "cta": "申请举牌接机"
      },
      {
        "id": "ticket-assistance",
        "category": "tickets",
        "featured": true,
        "title": "下一站去哪里？",
        "eyebrow": "机票 · 火车票 · 巴士票",
        "summary": "告诉我们您的路线和出行日期。我们将搜索可用选项，帮您买到合适的票。",
        "description": "没有一种价格适用于所有行程。我们会核实余票，并在您决定前发送包含服务费在内的完整报价。您只需在同意可用选项及其预订条件后付款。",
        "price": {
          "mode": "quote",
          "amount": null,
          "currency": null,
          "unit": "付款前确认全部费用",
          "billingUnit": null
        },
        "image": null,
        "imageAlt": null,
        "imageFit": null,
        "imageCaption": null,
        "facts": [
          "机票、火车票或巴士票",
          "按您的路线查询选项",
          "付款前提供完整报价"
        ],
        "includes": [
          "协助搜索可用选项",
          "协助预订您认可的选项"
        ],
        "extras": [
          "票价及服务费包含在您的单独报价中",
          "改签、退票及退款取决于所选票种的规则"
        ],
        "confirmBeforePayment": [
          "路线、日期、余票及乘客信息",
          "票价、行李（如适用）、服务费及总价",
          "预计出票时间及改签/退款条件"
        ],
        "timing": "在核实座位及乘客信息后，我们力争在付款确认后 15–30 分钟内出票。付款前我们会确认预计出票时间。",
        "requestProfile": "tickets",
        "cta": "帮我找票"
      }
    ],
    "form": {
      "title": "让我们来安排细节",
      "intro": "告诉我们您的计划。我们的团队将与您联系，确认可用性及全部费用。",
      "nameLabel": "您的姓名",
      "contactLabel": "一种联系方式",
      "contactPlaceholder": "带国家代码的电话、Telegram @用户名或电子邮箱",
      "dateLabel": "期望日期",
      "timeLabel": "期望时间",
      "countLabel": "出行人数",
      "noteLabel": "还有其他需求吗？（选填）",
      "submit": "发送我的申请",
      "sending": "正在发送您的申请…",
      "back": "返回服务",
      "priceLabel": "起价 — 并非确认的总价",
      "quoteLabel": "单独报价 — 现在无需付款",
      "privacy": "我们仅使用您的姓名、联系方式和申请内容来安排服务。请勿在此输入护照或银行卡信息。",
      "payment": "提交此表单不会向您收费，也不构成确认的预订。",
      "successTitle": "您的申请已提交。",
      "successText": "请保存您的申请编号。我们的团队将通过您提供的联系方式与您联系，确认可用性、全部费用及付款方式。",
      "networkError": "我们无法确认已收到您的申请。您的信息仍保留在此，请重试。",
      "rateLimitError": "近期已发送多个申请。请等待几分钟后再试。",
      "inactiveRoom": "此房间链接不可用。请向酒店索取最新的 MehmonGo 二维码。",
      "helpHint": "如需帮助联系 MehmonGo，请咨询酒店前台。"
    },
    "faq": [
      {
        "question": "我需要在本网站付款吗？",
        "answer": "不需要。请先发送申请。我们的团队会确认可用性、总金额及付款方式。您的酒店前台可能会按约定安排代收款项。"
      },
      {
        "question": "价格是按人计算的吗？",
        "answer": "专车接送按所示选项以每车计价。向导价格按每次约定的导览计算。付款前我们会确认人数及任何额外费用。"
      },
      {
        "question": "发送申请后预订就确认了吗？",
        "answer": "还没有。我们会与您联系，商定细节并说明如何确认预订。"
      },
      {
        "question": "可以更改或取消吗？",
        "answer": "条件取决于服务和供应商。付款前我们会说明任何更改或取消条款。"
      }
    ]
  }
};
